openapi: 3.0.1
info:
  title: Google Sheets Plugin API
  description: An API for reading, writing, and creating Google Sheets.
  version: v1

servers:
  - url: https://googlesheet-plugin.onrender.com

paths:
  /sheets:
    post:
      operationId: createSheet
      summary: Create a new spreadsheet.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: The title of the new spreadsheet.
      responses:
        "200":
          description: OK

  /sheets/{spreadsheetId}/values/{range}:
    get:
      operationId: getSheetValues
      summary: Read values from a sheet range.
      parameters:
        - name: spreadsheetId
          in: path
          required: true
          schema:
            type: string
        - name: range
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK

    put:
      operationId: updateSheetValues
      summary: Write values to a sheet range.
      parameters:
        - name: spreadsheetId
          in: path
          required: true
          schema:
            type: string
        - name: range
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                values:
                  type: array
                  items:
                    type: array
                    items:
                      type: string
      responses:
        "200":
          description: OK

components:
  securitySchemes:
    oAuth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/v2/auth
          tokenUrl: https://oauth2.googleapis.com/token
          scopes:
            https://www.googleapis.com/auth/spreadsheets: Read/write access to Sheets.

security:
  - oAuth: []

