openapi: 3.0.1
info:
  title: PDF Generator Plugin
  description: A plugin to generate PDF documents from text using a self-hosted server.
  version: v1
servers:
  - url: https://googlesheet-plugin.onrender.com
paths:
  /generate-pdf:
    post:
      operationId: generatePdf
      summary: Generate a PDF document from text content.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - content
                - filename
              properties:
                content:
                  type: string
                  description: "The text content to be written into the PDF. Use '\\n' for new lines."
                filename:
                  type: string
                  description: "The desired filename for the output PDF (e.g., 'report.pdf')."
                title:
                  type: string
                  description: "Optional metadata title for the PDF document."
                author:
                  type: string
                  description: "Optional metadata author for the PDF document."
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  filename:
                    type: string
                    description: The suggested filename for the generated PDF.
                  base64Data:
                    type: string
                    description: The generated PDF file, encoded as a Base64 string. The AI should offer this to the user as a download.
                  message:
                    type: string
